---
title: "DS 5010 - Summer 2022"
---

## Introduction to Programming for Data Science

**Schedule:** Tuesdays/Thursdays 6:00 pm - 7:30 pm

**Location:** Zoom Meetings (link via Canvas or Piazza)

**Dates:** May 09, 2022 - August 20, 2022

**Instructor:** [**Kylie Bemis**](http://www.ccis.northeastern.edu/people/kylie-ariel-bemis/) (she/her) |
k.bemis@northeastern.edu | 
*Office Hours:* See Piazza

**Piazza:** Questions and lecture material are handled via [Piazza](https://piazza.com/northeastern/summer2022/ds5010bemis) | Sign up https://piazza.com/northeastern/summer2022/ds5010bemis

**Canvas:** Course schedule and assignments are available via [Canvas](https://northeastern.instructure.com/courses/111123) | Log https://northeastern.instructure.com/courses/111123

**Teams:** Office hours are held virtually via [Microsoft Teams](https://teams.northeastern.edu) | Log in at https://teams.northeastern.edu

**Required Textbooks:**

- *Learning Python*. Mark Lutz. O'Reilly Media, 2013.

*(Required reading excerpts will be made available on Piazza.)*

**Supplementary Textbooks:**

- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*. Wes McKinney, O'Reilly Media, 2013.

- *Introduction to Algorithms, 3rd edition*. Thomas Cormen, Charles Leiserson, Ronald Rivest and Clifford Stein, MIT Press, 2009.

*(Required reading excerpts will be made available on Piazza.)*

**Academic integrity:** Be familiar with the university's [academic integrity policy](http://www.northeastern.edu/osccr/academic-integrity-policy/) on cheating and plagiarism.

***

## Overview

The course is a hands-on introduction to the fundamentals of programming, data structures and algorithms for data sciences. The course encompasses programming basics such as functions, data structures, and algorithms; and their use in design and implementation of data science applications. Fundamentals of discrete mathematics for programming with data will be introduced where appropriate. The course will also introduce students to programming as a collaborative discipline. The course will develop programming experience in Python.

**Students are required to get a B or above in the placement courses in order to progress into the core courses in the degree program. Students that do not achieve a B or better in the placement courses will be required to retake the courses.**

***

## Topics

- Control flow and program logic
- Data types (lists, dictionaries, tuples, sets)
- Data structures (arrays, queues, stacks, hash tables, trees, etc.)
- Computational complexity
- Files and I/O
- Object-oriented programming
- Number systems and representation (binary, hex, floating point)
- Programming with vectors, arrays, and matrices
- Source control and version control systems
- Unit testing

***

## Policies

#### *General*

Please let me know if you use a different name or pronouns from what appears the class roster. You may use a preferred name on Piazza and when submitting assignments and exams, but please be consistent and inform the instructors. The Northeastern [LGBTQA Center](https://studentlife.northeastern.edu/lgbtqa/) can provide resources for [changing your name and gender marker in the Northeastern system](https://www.northeastern.edu/ouec/training-and-education/gender-identity-personal-pronouns-syllabus-guidance/).

Please reach out to me early if you have difficulty keeping up with class material or completing assignments for personal reasons. The [We Care](https://studentlife.northeastern.edu/we-care/) program at Northeastern University is a resource available to you in times of stress.

All students are expected to abide by the university's [academic integrity policy](http://www.northeastern.edu/osccr/academic-integrity-policy/) and respect Northeastern's [commitment to diversity and inclusion](https://www.northeastern.edu/academic-plan/strategic-themes/diversity-and-inclusion/).

Northeastern University strictly prohibits discrimination or harassment on the basis of race, color, religion, religious creed, genetic information, sex, gender identity, sexual orientation, age, national origin, ancestry, veteran, or disability status. [Please review Northeastern's Title IX policy](https://www.northeastern.edu/ouec/), which protects individuals from sex or gender-based discrimination, including discrimination based on gender-identity. Faculty members are required to report all allegations of sex/gender-based discrimination to the Title IX coordinator.

*Please be kind and respectful to your fellow students regardless of identity or background. Students are expected to respect and use other students' names and pronouns.*

## Technology

#### *Zoom*

Classes will be broadcast synchronously via Zoom. Synchronous attendance is strongly encouraged for class participation and Q&A. For students that cannot attend synchronoucly, cloud recordings will be available from the Zoom Meetings link on Canvas.

#### *Piazza*

Course administration, including all questions, course materials, and course announcements will be handled via Piazza.

Please do not email instructors or TAs directly -- use Piazza for your questions and queries instead. This allows us to track all course-related correspondence in a single location.

General questions that may be useful to other students should be posted to the whole class. If your question is specific to you, or includes a partial solution, then post it to instructors only.

Please see [this Stackoverflow guide](https://stackoverflow.com/help/how-to-ask) for how to ask a good question.

#### *Canvas*

Assignments, quizzes, and grading will be handled via Canvas.

All assignments and quizzes will be posted on Canvas, and must be submitted on Canvas by the posted due date. Please do not email completed assignments or quizzes to instructors or TAs, or post them on Piazza.

#### *Microsoft Teams*

Virtual office hours will be handled via Microsoft Teams. During  scheduled office hours or by appointment, instructors and TAs will be available for live chat or video call on Microsoft Teams.

****

## Homework

Homework assignments will be assigned every 1-2 weeks and must be completed individually. Each homework is due online via Canvas by the deadline for the assignment on Canvas. (If deadlines differ from the outlined schedule, always use the assignment deadline.)

Some aspects of the homework may be discussed with each other, but they should be completed individually, and your submitted work should be your own. Sharing of worked solutions will not be tolerated and will be considered cheating. Plagiarised solutions will receive a zero. Solutions with a very high degree of similarity with another past or current student's will be considered plagiarism, and will be treated accordingly.

***

## Quizzes

There will be occasional cumulative quizzes during the semester. All quizzes will be completed online via Canvas on the dates scheduled on Canvas, and will replace a class meeting.

***

## Project

There will be a final programming project completed in small teams. Project guidelines will be posted on Piazza and discussed in class.

***

## Late work and grading

Late assignments will be considered on a case-by-case basis. No-penalty extensions may be given if requested at least 48 hours in advance of the due date with a reasonable justification.

*__Petitions for re-grades must be made in writing via Piazza private message no later than 1 week after receiving the original grade. The petition must clearly explain why a re-grading is justified. The new grade may be lower than the original grade.__*

*Before petitioning the instructor for a re-grade, students should first contact the grader to make sure they understand why they lost points.*

***

## Grade scale

**Students are required to get a B or above in the placement courses in order to progress into the core courses in the degree program. Students that do not achieve a B or better in the placement courses will be required to retake the courses.**

The grade in this class is distributed as follows:

- Homework: 30%
- Quizzes: 30%
- Project: 30%
- Participation: 10%

Final grades will follow the following scale:

- A : <= 100.0
- A-: < 94.0
- B+: < 90.0
- B : < 87.0
- B-: < 84.0
- C+: < 80.0
- C : < 77.0
- C-: < 74.0

__*These scales are subject to change at the discretion of the instructor.*__

