---
title: "DS 5500 - Fall 2023"
---

## Data Science Capstone

**Schedule:** Tue/Fri 3:25pm - 5:05pm

**Location:** West Village H 110 (+ Zoom)

**Dates:** Sep 6, 2023 - Dec 16, 2023

**Instructor:** [**Kylie Bemis**](http://www.ccis.northeastern.edu/people/kylie-ariel-bemis/) (she/her) |
k.bemis@northeastern.edu | 
*Office Hours:* Microsoft Teams (see "Staff" tab of Piazza Resources for schedule)

**Piazza:** Questions and lecture material are handled via [Piazza](https://piazza.com/northeastern/fall2023/ds5500bemis) | Sign up at https://piazza.com/northeastern/fall2023/ds5500bemis

**Canvas:** Course schedule and assignments are available via [Canvas](https://northeastern.instructure.com/courses/157406) | Log in at https://northeastern.instructure.com/courses/157406

**Teams:** Office hours are held virtually via [Microsoft Teams](https://teams.northeastern.edu) | Log in at https://teams.northeastern.edu

**No Required Textbooks**

**Academic integrity:** Be familiar with the university's [academic integrity policy](http://www.northeastern.edu/osccr/academic-integrity-policy/) on cheating and plagiarism.

***

<span style="color:red">*__IMPORTANT: Due to unforeseen circumstances, I will be teaching remotely for the start of this semester. Please see Canvas for Zoom links, and check Piazza for updates.__*</span>

## Overview

The course offers students a capstone opportunity to practice data science skills learned in previous courses, and build a portfolio. Students practice visualization, data wrangling, and machine learning skills by applying them to semester-long term projects on real-world data. Students may either propose their own projects or choose from a selection of industry options. Emphasis on the overall data science process, including identification of the scientific problem, selection of appropriate machine learning methods, and visualization and communication of results. There will be occasional lectures on special topics such as visualization, communication, and data science ethics.


***

## General Policies

#### *Name and pronouns*

Please let me know if you use a different name or pronouns from what appears the class roster. You may use a chosen name on Piazza and when submitting assignments and exams, but please be consistent and inform the instructors. The Northeastern [LGBTQA Center](https://studentlife.northeastern.edu/lgbtqa/) can provide resources for [changing your name and gender marker in the Northeastern system](https://www.northeastern.edu/ouec/training-and-education/gender-identity-personal-pronouns-syllabus-guidance/).

*Please be kind and respectful to your fellow students regardless of identity or background. Students are expected to respect and use other students' chosen names and pronouns.* All students are expected to respect Northeastern's [commitment to diversity and inclusion](https://www.northeastern.edu/academic-plan/strategic-themes/diversity-and-inclusion/).

#### *Mental and physical health*

Please reach out to me *__as early as possible__* if you have difficulty keeping up with class material or completing assignments for personal reasons. I am able to provide more accomodations and options for you earlier in the semester than later in the semester when deadlines are looming. The [We Care](https://studentlife.northeastern.edu/we-care/) program at Northeastern University is another resource available to you in times of stress.

#### *Academic integrity*

All students are expected to abide by the university's [academic integrity policy](http://www.northeastern.edu/osccr/academic-integrity-policy/). Plagiarised work will not receive points in this course and may be reported. Authorized use of outside resources (including but not limited to third-party code) *__must__* be cited.

#### *Title IX*

Northeastern University strictly prohibits discrimination or harassment on the basis of race, color, religion, religious creed, genetic information, sex, gender identity, sexual orientation, age, national origin, ancestry, veteran, or disability status. [Please review Northeastern's Title IX policy](https://www.northeastern.edu/ouec/), which protects individuals from sex or gender-based discrimination, including discrimination based on gender-identity. Faculty members are required to report all allegations of sex/gender-based discrimination to the Title IX coordinator.

#### *Remote Instruction*

*__IMPORTANT: Due to unforeseen circumstances, I will be teaching remotely for the start of this semester. Please see Canvas for Zoom links, and check Piazza for updates.__*

Students may participate remotely via online Zoom meetings. All course content can be accessed and completed remotely. However, synchronous attendance and participation (i.e., during the regularly scheduled class time in the Boston time zone) is expected for this project-based course. *Students are still responsible for making sure they satisfy any college requirements for in-person enrollment.*

*__The instructor may teach further class sessions fully remotely if the need arises.__*

*__Please do not come to class in-person if you are experiencing symptoms of COVID-19 or other flu-like illness.__*

***

## Technology

#### *Piazza*

Course administration, including all questions, course materials, and course announcements will be handled via Piazza.

Please do not email instructors or TAs directly -- use Piazza for questions instead. This allows us to track all course-related correspondence in a single location.

General questions that may be useful to other students should be posted to the whole class. If your question is specific to you, then post it to instructors only.

Please see [this Stackoverflow guide](https://stackoverflow.com/help/how-to-ask) for how to ask a good question.

#### *Canvas*

Assignments and grading will be administered via Canvas.

All assignments will be posted on Canvas, and must be submitted on Canvas by the posted due date. Please do not email completed assignments to instructors or TAs, or post them on Piazza.

#### *Zoom*

Classes will be broadcast synchronously via Zoom. Remote students can use Zoom to attend class virtually. The instructor may teach some class sessions fully remotely if the need arises.

#### *Microsoft Teams*

Virtual office hours will be held via Microsoft Teams. During scheduled office hours or by appointment, instructors and TAs will be available for live chat or video call on Microsoft Teams.

***

## Homework

This class has no traditional homework assignments. Students are expected to focus on their capstone project(s). Some peer review and participation assignments may be assigned.

***

## Quizzes

This class has no quizzes or exams.

***

## Project

Students will propose and complete two project phases in small groups. Projects may consist of a single semester-long project split into two phases, or two smaller half-semester projects.

Project guidelines will be posted on Piazza and discussed in class.

***

## Peer review

Peer review is a major component of this course. Students are expected to provide oral and written feedback on their classmates’ projects, both on the scientific content and on the effectiveness of their communication.

Rubrics will be posted on Piazza and discussed in class.

***

## Late work and grading

Late assignments will not be accepted. Extensions may be given on a case-by-case basis if requested at least 48 hours in advance of the due date with a reasonable justification.

Petitions for re-grades must be made in writing via Piazza private message no later than 1 week after receiving the original grade. The petition must clearly explain why a re-grading is justified. The new grade may be lower than the original grade.

Before petitioning the instructor for a re-grade, students should first contact the grader to make sure they understand why they lost points.

***

## Grade scale

The grade in this class is distributed as follows:

- Projects: 80%
- Participation: 20%

Final grades will follow the following scale:

- A : <= 100
- A-: < 94
- B+: < 90
- B : < 87
- B-: < 84
- C+: < 80
- C : < 77
- C-: < 74

__*These scales are subject to change at the discretion of the instructor.*__

