---
title: "Open Letter on Public Data"
date: February 5, 2025
---

***

To the American People:

---

#### *Preamble*
 
As a statistician, I can’t overstate the dangers of the crisis in the federal government right now.

As a private citizen of the USA, I have my personal concerns as well.

As a Native American and enrolled member of the Zuni Tribe, I could write about the attacks on our sovereignty and citizenship through the illegal actions of ICE.

As a transgender woman, I could write about the attacks on my humanity through the erosion of our civil rights and attempted erasure of transgender Americans from public life.

As an autistic person, I could write about the existential threat that the nomination of RFK Jr. to the Department of Health and Human Services poses to disabled and neurodivergent Americans.

As an indigenous person, I could write about the utter heartbreak and humanitarian atrocity that is the threat of ethnic cleansing of the Palestinian people from their homeland.

But I am writing this letter as a professional statistician to warn the American people of the clear and present danger that the Trump administration poses to our country’s health, security, and sustainability as a nation.

This perspective is wholly my own and does not represent the official position of any institution. But I do sincerely hope my colleagues are prepared to speak up and uphold their ethical responsibilities to their respective fields.

---

#### *Perspective*
 
I am a statistician by training. As a professor, I teach data science. As a researcher, I develop statistical methods with applications ranging from cancer detection to drug discovery.

As a professional statistician, I have an ethical responsibility to protect and respect the rights of data subjects and those directly affected by statistical practices; I have an ethical responsibility to stakeholders in collection, release, and dissemination of data; I have a professional duty to report statistical misconduct and violations of the right of data stakeholders.

Today, those data subjects and stakeholders are the American people. The institutions to whom I would report this misconduct are the very institutions perpetrating it.

So I am addressing this letter to my fellow Americans directly.

The Trump administration — through the Department of Government Efficiency (DOGE) and other arms of the executive branch — is systematically purging and misappropriating data that belongs to the American people. These actions recklessly endanger the American people.

##### Health
 
These actions put the health of the American people at risk through the deletion of vital public health data. Researchers in the USA and around the world depend on public health data from agencies like the Centers for Disease Control and Prevention (CDC).

Much of this data has now been deleted as a direct result of President Trump’s executive orders.

With the world only five years removed from a devastating global pandemic in COVID-19, and with imminent warnings of another in H5N1 bird flu, it is beyond irresponsible and unethical to delete this public health data, which was collected with taxpayer money for the benefit of the American people. It will delay timely response to public health issues. It will cost lives.

As a transgender statistician, I must also note that while these executive orders are primarily designed to target transgender Americans, the deleted data and effects are not limited to transgender Americans. This affects healthcare research and response for everyone.

Furthermore, the Trump administration’s interference in the National Institutes of Health (NIH) and National Science Foundation (NSF) will have dire and long-lasting consequences on health. These are the institutions that make America a world leader in health and biomedical research and scientific research generally. Private companies rely on the foundational research funded by these institutions. The discoveries that power breakthrough health treatments come from publicly-funded research driven by scientific merit rather than profitability.

The deletion of this data and defunding of these institutions will make America less healthy, possibly for decades for come. Many of us will lose our lives or the lives of loved ones to deaths that could have been treated or prevented.

##### Security
 
These actions put the security of the American people at risk through the unauthorized and illegal access of the private data of US citizens. The Treasury Department has reported that officials from DOGE have access to sensitive Treasury Department financial systems that process trillions of dollars to Americans in the form of tax refunds, social security payments, Medicare and Medicaid payments, and more. Elon Musk and DOGE officials do not have proper security clearance or authorization to access this private data, and they are operating without any transparency or oversight.

This is a cybersecurity risk that is unparalleled and unprecedented in the history of the USA.

This is the private data of private American citizens like you and me. It is now being accessed by an unelected billionaire and untested interns without the cybersecurity expertise and experience to safeguard this sensitive data against threats both foreign and domestic.

Furthermore, the Trump administration’s interference in the National Institutes of Health (NIH) and National Science Foundation (NSF) will have consequences for American security too.

Early in his term, President Trump correctly identified innovation in AI as vital to American economic and national security. However, the actions of the Trump administration are in direct opposition to innovation in AI research. While the most well-publicized AI models like ChatGPT and Gemini come from the private sector, the foundational research behind these models happens at research universities. Researchers at OpenAI and Google build on the doctoral research they did as university students to develop state-of-the-art AI models for American companies.

The USA attracts the best researchers in the world through institutions like the NSF and the NIH. Without these institutions and their funding, the best researchers in the world will go elsewhere. Even short term delays in funding can have a long-term chilling effect and can lead to an exodus of intellectual talent from the USA, including AI researchers.

The American people are less safe today due to the actions of the Trump administration.

The continued action of Elon Musk and DOGE to access extremely sensitive data represents an ongoing cybersecurity threat against the American people.

##### Sustainability
 
These actions put the sustainability of the USA itself at risk. Regardless of your beliefs about anthropogenic climate change, it is self-evident that extreme weather events and natural disasters are becoming increasingly frequent.

In the wake of catastrophic fires in California stemming from critically dry conditions, the Trump administration and DOGE are now targeting the National Oceanic and Atmospheric Administration (NOAA), the federal agency responsibly for tracking weather and climate data. This data drives not only weather forecasts for the general public but also vital monitoring for extreme weather events and natural disasters.

Deleting this data poses a risk to our sustainability as a nation and to the lives of the people in the communities affected by these events. It will affect the ability to rapidly respond to coming natural disasters. This, too, will cost lives.

---

#### *Plea*
 
I ask my colleagues and the American people to speak up about the reckless misconduct by the Trump administration and by Elon Musk and DOGE.

This is our data. This is the biggest data breach in history. It represents an ongoing cybersecurity threat. And it endangers every single US citizen.

I am writing this letter because I am fulfilling my ethical duty as a statistician by doing so.

I ask the US Congress and the Courts to fulfill theirs.

---

Sincerely,

Prof. Kylie Ariel Bemis, PhD
