---
title: "Open Letter to Northeastern"
date: February 22, 2025
---

***

To the Northeastern community:

---

I see you. I’m here for you.

I’m an Assistant Teaching Professor in the Khoury College of Computer Sciences. I came here in 2016 as a postdoctoral researcher. I joined as teaching faculty in 2019. I’ve served Northeastern University for nearly a decade of my life. In that time, I’ve developed the core courses in our Masters of Data Science program, and by my count I’ve taught over a thousand students in our graduate program. My great hope is that I’ve instilled a sense of data ethics and civic responsibility in the students I’ve taught.

I’m proud to be a member of the Northeastern University community.

I’m proud of my Northeastern students who have chosen to use data science and their capstone projects to bring attention to issues of social justice or to serve their local communities or nonprofit organizations.

I’m proud of the Northeastern graduate student workers who have organized across colleges to protect the civil rights and fair wages of their fellow graduate student workers.

I’m proud of the Northeastern students who have raised their voices to speak out for the human rights of Palestinians and of all indigenous peoples.

I’m proud of my Northeastern colleagues who have fought so hard for diversity, equity, and inclusion at Northeastern University and worldwide.

And I am so proud of all my Northeastern colleagues who have stayed up sleepless nights wracking our brains trying to think of ways to protect our most vulnerable students during this unprecedented crisis.

For too many years, we Americans have taken our democracy for granted.

We now live in a time when the President of the United States has openly aligned his administration with the dictators and authoritarian regimes of the world, and seems to seek to become a king himself.

But America has no kings.

This is the simple truth I ask our leadership to say out loud.

I believe Northeastern University deserves leadership with the courage to say this out loud.

That Donald Trump is not a king. That America has no kings. That Northeastern University will fight like hell to protect its most vulnerable students, faculty, and staff — and especially its immigrant students and its students of color and its queer and transgender students — from the violent executive overreach and state-sanctioned terrorism of a would-be dictator.

I believe Northeastern University deserves leadership who are transparent in what they tell the university’s students, faculty, and staff about the university’s legal strategy to fight for our research, for our financial aid, for our safety from ICE, for our human rights and civil rights as transgender Americans, and for our democracy.

I believe Northeastern University deserves leadership who are willing to respect the rights of the university’s students, faculty, and staff to peaceably assemble on campus, to protest for their rights or for the rights of others, and to petition their university’s leadership for a redress of grievances.

I believe Northeastern University deserves leadership who are unwilling to obey in advance when faced with unconstitutional or illegal executive orders, because obeying in advance only teaches a would-be dictator what power you’re willing to yield to him voluntarily.

I believe Northeastern University deserves leadership who are ready and willing to meet this moment with the bravery and fight it deserves, because fascism must always be fought with unyielding fury.

But even without that leadership, I believe in the Northeastern University community.

I believe in the Northeastern community who will turn to our immigrant peers and our peers of color and our queer and transgender peers and say you are loved and you are safe with me.

I believe in the Northeastern community who will organize and take to the streets to fight like hell for our research, and our financial aid, and our safety from ICE, and our human rights and civil rights as transgender Americans, and for our democracy.

I believe in the Northeastern community who are standing to meet this moment with the bravery and fight it deserves, because fascism must always be fought with unyielding fury.

I see you. I thank you. I’m with you.

---

Sincerely,

Prof. Kylie Ariel Bemis, PhD
