---
title: "Open Letter to Academia"
date: February 8, 2025
---

***

To my academic colleagues:

---

We have dedicated our lives to teaching, research, and service. Most of us have chosen this path because we believe passionately in what we do. We believe in the importance of higher education. We believe in the importance of our research. We believe in the broader impact of our work.

Many of us have seen Presidential administrations come and go. We have persevered through changing Presidential priorities, and we have coped with Congressional budget cuts. We have worked to protect our most vulnerable students through shifting legal landscapes, and we have helped them navigate different immigration policies. We have done our jobs as the wheel of democracy turns.

That is not what is happening now.

The Trump administration is acting through illegal executive orders. By usurping the federal budget and ignoring Congressional mandates, the Trump administration is attempting to exercise powers that do not belong to the executive branch. This is a threat not only to academia but to democracy itself.

As we navigate this new political landscape, it is vitally important that we do not allow our institutions to ignore the gravity and scope of this constitutional crisis. Traditional lobbying will not work, because the Trump administration is not using legal means to enact their agenda.

For example, the federal funding freeze affecting NSF and NIH grants among others was only lifted due to a federal judge’s restraining order. The Trump administration’s orders to the NSF and NIH to stop funding DEI-related research activities directly violates these agencies’ Congressional mandates. Even the budget cuts to NIH “indirect costs” violate the NIH’s fiscal responsibilities as set by Congress.

We need to hold our institutions accountable to their missions and to the law. Obeying these illegal executive orders in advance will not work and instead shifts legal liability from the Trump administration to our academic institutions. The only viable path forward is to petition our institutions to bring immediate legal action against the Trump administration. Anything less is performative.

Many of us are understandably afraid. None of us wants to become a target. Institutions do not want to become targets. But we are already being targeted. The Trump administration — through Elon Musk and the so called Department of Government Efficiency — is already targeting the Department of Education after thoroughly dismantling USAID. Higher education as a whole is a target.

Now is the time to speak up.

We are experts in our fields. Many of us are members of professional societies with ethical codes that give us a responsibility to report harmful misconduct in our fields, especially when it may impact public safety. We have a moral obligation to speak up.

If you are a computer scientist, speak up about the unprecedented cybersecurity threat posed by the actions of Elon Musk and DOGE in gaining access to sensitive government systems.

If you are an AI researcher, speak up about the impact of cutting NSF funding on AI research and the dangers of using AI and LLMs in sensitive government systems, as Elon Musk is proposing.

If you are a health or biomedical researcher, speak up about the grave dangers to public health posed by funding cuts to the NIH, by the lack of new data from the CDC, and by RFK Jr.

If you are a climate researcher, speak up about lives that may be lost to natural disasters if we lose access to data from agencies like the National Oceanic and Atmospheric Administration.

If you are an economics professor, speak up about the impact of eliminating the Consumer Financial Protection Bureau or the dangers of the Federal Reserve potentially losing political independence.

If you are an arts or humanities professor, speak up about the history of book bans and how authoritarian regimes use suppression of the arts and humanities as a tool of political oppression.

If you are a media professor, speak up about the freedom of the press and how the removal of protections for journalists covering public officials is a danger to democracy.

If you are a law professor, speak up about the illegality of these executive orders and the grave dangers that “unitary executive theory” as espoused by the Trump administration poses to the separation of powers and the system of checks and balances set forth in the Constitution.

The list goes on.

Talk to your institutional leadership. Talk to your senators and your Congressional representatives and your attorneys general. Talk to the press. Talk to your friends and your family. Talk to your community.

Academia has always been the enemy of authoritarianism and autocracy.

The fight has come to us. It’s time to stand up.

---

Sincerely,

Prof. Kylie Ariel Bemis, PhD
