---
title: "Selected Publications"
---

***

- **_K. A. Bemis_**, M. C. Foell, D. Guo, S. S. Lakkimsetty, and O. Vitek. "Cardinal v3 - a versatile open source software for mass spectrometry imaging analysis."  _Nature Methods_. 2023. https://doi.org/10.1038/s41592-023-02070-z

- D. Guo, M. C. Foell, **_K. A. Bemis_**, and O. Vitek. "A noise-robust deep clustering of biomolecular ions improves interpretability of mass spectrometric images."  _Bioinformatics_. 2023. https://doi.org/10.1093/bioinformatics/btad067

- D. Guo, **_K. A. Bemis_**, C. Rawlins, J. Agar, and O. Vitek. "Unsupervised segmentation of mass spectrometric ion images characterizes morphology of tissues."  _Bioinformatics_. 2019. http://doi.org/10.1093/bioinformatics/btz345

- **_K. A. Bemis_**, D. Guo, A. Harry, M. Thomas, I. Lanekoff, M. Stenzel-Poore, S. Stevens, J. Laskin, and O. Vitek. "Statistical detection of differentially abundant ions in mass spectrometry-based imaging experiments with complex designs." _International Journal of Mass Spectrometry_. 2019. http://doi.org/10.1016/j.ijms.2018.07.006

- **_K. A. Bemis_** and O. Vitek. (2017). "_matter_: an R package for rapid prototyping with larger-than-memory datasets on disk." _Bionformatics_. 2017. http://doi.org/10.1093/bioinformatics/btx392

- **_K. D. Bemis_**, A. Harry, L. S. Eberlin, C. Ferreira, S. M. van de Ven, P. Mallick, M. Stolowitz, and O. Vitek. (2016). "Probabilistic Segmentation of Mass Spectrometry (MS) Images Helps Select Important Ions and Characterize Confidence in the Resulting Segments." _Molecular & Cellular Proteomics_. 2016. http://doi.org/10.1074/mcp.O115.053918

- S. van de Ven, **_K. D. Bemis_**, K. Lau, R. Adusumilli, U. Kota, M. Stolowitz, O. Vitek, P. Mallick, S. S. Gambhir. (2016). "Protein biomarkers on tissue as imaged via MALDI mass spectrometry: A systematic approach to study the limits of detection." _Proteomics_. 2016. http://doi.org/10.1002/pmic.201500515

- **_K. D. Bemis_**, A. Harry, L. S. Eberlin, C. Ferreira, S. M. van de Ven, P. Mallick, M. Stolowitz, and O. Vitek. "_Cardinal_: an R package for statistical analysis of mass spectrometry-based imaging experiments." _Bioinformatics_. 2015. http://doi.org/10.1093/bioinformatics/btv146
