---
title: "Rally for Truth, Light, and Courage: 'Be the light'"
date: November 15, 2025
---

***

We are here today to rally for light, truth, and courage, because we will need these things. We need these things, because America is sick with the illness of tyranny, and these are the precursors of liberty that tyranny must extinguish in order for fascism to flourish. We need these things, because these are the things that have been forsaken by America’s leaders, from the halls of the House and the Senate, to the halls of our academic institutions.

We are here, because the very same institutions that were once meant to instill and nurture these values in the minds of the next generation have become too comfortable with the encroachment of fascism upon their sacred mission.

We must tell the truth, because the truth will set us free, and — as a great philosopher once said — “none but ourselves can free our minds.” That is why there is nothing a tyrant fears more than truth. There is no freedom when two plus two is five. There is no freedom when your mind is not your own. That is why a tyrant must do everything he can to snuff out the truth and drown it in an ocean of lies.

Unlike our forebears, we must contend not only with the canned lies of traditional propaganda like Fox News, but also the rise of artificially intelligent machines that can manufacture misinformation on a scale unprecedented in human history. But artificial intelligence is just one more postmodern miracle that would not exist without the academic freedom to pursue truth, without the funding for scientific research, or without the brilliance of yesterday’s international students who became today’s immigrant entrepreneurs.

So shout the truth from every mountaintop and every molehill until we are free.

We must have courage, because the machine of fascism is fueled by fear. And we must have courage, because our leaders are cowardly. They believe if only they forsake the most vulnerable among us, then they will be safe. But these are the lies that feed the fascist machine.

We must have the courage to fight for our international and immigrant students, and our transgender and nonbinary students, and our Black and Indigenous students, and our disabled and neurodivergent students, because we all know how the poem ends if we don’t. Because we learned about history and the machinery of fascism and the geography of genocide in school back when our leaders still had the courage to condone the teaching of truth.

So be as brave and courageous as you can possibly be.

I wish we did not need to be here today. But history reminds us this struggle is not new. Over two hundred years ago, a lawyer from Massachusetts wrote: “I must study Politicks and War, that my sons may have liberty to study Mathematicks and Philosophy. My sons ought to study Mathematicks and Philosophy. . . in order to give their children a right to study Painting, Poetry, [and] Musick.”

But I disagree with Mr. Adams on one point. I don’t believe any revolution can be won without poetry and art, because art is the most potent vehicle of truth. A poem is a petition for courage.  Whether you study art, science, or history, I believe every student in America is a light against the shadow of tyranny. Because you are the future, and fascism is fundamentally a bet against the future.

And I would not want to bet against the fight I feel in your hearts or the light I see in your eyes.

In the words of a student activist who once marched on Edmund Pettus Bridge in Selma: “You are a light. You are the light. Never let anyone — any person or force — dampen, dim, or diminish your light.”

So go be the light, and shine as brightly as you dare.

---

~ Dr. Kylie Ariel Bemis
