---
title: "Boston ICE Tea Party: 'No Kings! No tariffs! No ICE!'"
date: December 16, 2025
---

***

Twenty-five decades and two years ago, a few dozen revolutionaries engaged in an act of civil disobedience in defiance of the most powerful empire in the world.

Though we act tonight with symbolic reverence for that history, we do not protest to honor the past, but to bet our hopes on a future that is not defined by old glory or populist visions of illusory greatness, but is instead shaped by our shared will that a nation conceived in blood and liberty is a promise we must renew every generation, or die trying.

Our generation’s struggle is not against some distant empire, nor even against the tyrant who resides in our White House, whose crimes echo our American revolution. Our struggle is against the forces of greed and fear that convince our fellow Americans that freedom is a zero-sum game of winners and losers instead of the common destiny of a united people.

We live in a nation born in blood and genocide, built upon bondage and slavery, and sustained by prejudice and partisanship. But we must believe that the promise of liberty — the very promise of America — is more powerful than these things, if only we are daring enough to confront them. If only we are patriotic enough to decide America can be better, must be better, must be more than the sum of its past, then we must fight for that future.

Though the night is dark and cold and the year is at an end, a new dawn is only a promise and a prayer until we bring that future into being. It is up to us to resolve the world on which a new sun will rise, so these are our new year’s resolutions: No kings! No tariffs! No ICE!

---

~ Dr. Kylie Ariel Bemis
