---
title: "Stand Up for Science: 'Rebellions are built on hope'"
date: March 7, 2025
---

***

My fellow scientists, American citizens, and dear allies of democracy: it is my honor to stand here with so many of you today. We are here to raise our voices in a righteous battle to protect American science and democracy from the violent whims of a billionaire who now occupies our White House and the madness of a president who has crowned himself king, who has raised a sword against the very scientific achievements that have helped define America’s greatness, and who must now be stopped at all costs.

It is appropriate that so many of us have gathered here in Boston, the very same shining city on a hill that the Puritans and American presidents past and present have invoked as a vision of the American dream.

Three score and three years ago, one of those great Americans, whose presidential library in this shining city has now been shuttered by the tyrant in the White House, proposed an impossible task to a generation who also bore witness to the violent struggle and blessed awakening of racial justice in this country. That great American called upon a generation to cast off the chains of earthly gravity and put an American on the moon within the decade, not because it is easy, but because it is hard. That dream itself — one of the greatest feats of science and engineering humankind has ever attempted — was only possible because of the tireless work of Black women scientists. Scientists like Katherine Johnson, who at the beginning of that decade could still not reliably cast her vote in the ballot box, who only 4 years after the passage of the Voting Rights Act, computed the equations that guided Apollo 11 to break free of its terrestrial bonds, sent it forth 239,000 miles across the vastness of space to plant an American flag on lunar soil, and returned it and our astronauts safely back to this blue planet we call home.

Now it is up to us to do the hard things, to confront the injustices of our own time, to take up the struggle of our forefathers and foremothers, and live up to the tenacity of those who came before us.

Like those brave, marginalized scientists of the past who relentlessly pushed this country forward, many of us here know what it is the be the only one in the room. The only woman. The only person of color. The only Indigenous person. The only queer person. The only transgender person. So do I know the feeling of being the only one.

When I received my final diploma from Purdue University, nearly 9 years ago now, I became — to the best of my knowledge — the first Native American to achieve a doctorate in statistics. Since then, I have been honored with multiple awards, taught thousands of students, and I have spoken at the Boston Museum of Science during its celebration of Native American Heritage Month last year. I have developed software and machine learning models used by hundreds of other scientists around the world to decipher the molecular mysteries of cancer, PTSD, and aging. In the days following the inauguration of the president who would be king, I labored over a research grant proposal for the National Institutes of Health while watching the confirmation hearings of the man who would soon dismantle my work. Nonetheless, I persevered. I submitted that grant.

But the tyrant now occupying our White House would rather that scientists like me would not exist. The tyrant now occupying our White House would rather that people like me would be erased from public life entirely. The tyrant in the White House would rather wipe all of our scientific achievements from history than face the possibility that a transgender woman from Zuni Pueblo could achieve what mediocre white men did not. These are the injustices of our time. This is the great struggle we face.

As a country, we stand now on the precipice of an abyss. We have emerged from the depths of one global pandemic, only to be facing down the looming threat of another one, while the American scientists who could protect us are either unemployed or must work with their hands bound behind their backs and their mouths gagged by the muzzle of an authoritarian regime. We have eradicated terrible illnesses that once ravaged our nation and the world, only to see them re-emerge, as the reins of our healthcare system are handed to a conspiracy theorist who believes I am autistic only because I am vaccinated. And even as I address you now, a billionaire oligarch continues to dismantle our institutions of science, education, and public safety.

And where, we may ask, are our allies? Where are the pharmaceutical companies that profit from our research? Where are the technological giants of Silicon Valley who have built their artificial intelligence empires on the backs of academics like us? Where are the universities that purport to support us but remain silent even as their faculty and students are under attack? Where are our colleagues who have buried their heads in the sands of ignorance and pretend that they are safe while we are not?

But even as we stare into the abyss, I have hope. Because we are here together. Because science is one of the undying flames that lights the lanterns of Liberty. Because where some would see despair, I see rebirth. For too long, we scientists have feared to enter the political fray. For too long, our endeavors have been misunderstood by the public. For too long, we have let the propaganda machine of fascism spreads disinformation and lies.

No more. No more.

No longer can we stay silent while we witness the coup of a would-be king. No longer can we stay silent while the tyrant in the White House tramples on our work. No longer can we stay silent while the ministers of disinformation dismantle scientific truth. No longer can we stay silent while the pharmaceutical companies and the insurance companies exploit our work and hold American patients hostage to the almighty dollar. No longer can we stay silent while the technological giants of Silicon Valley ignore every ethical tenet of artificial intelligence, intellectual property, and data privacy. No longer can we stay silent while a billionaire oligarch deletes the data and scientific services that belong to the American people. No longer can we stay silent, my friends.

That is why we are gathered here in Boston, one of the brightest beacons of biomedical research in the world, where I count my collaborators across myriad hospitals and research institutions across this great city. We are here because we will not stay silent. We are here because we will fight. We are here because science will fight.

And if we are to fight, we must bring our allies.

We must pull our colleagues’ heads from the sands of ignorance. We must hold our academic institutions accountable to our communities. We must become political and call our senators and our representatives and our mayors and our governors and our attorneys general and ask them to fight for us too. We must speak to journalists and tell them our stories.

We must go out and speak the truth in every corner of our communities, because truth is the language of Liberty and the very essence of the scientific endeavor.

But we must not stop there. If we are to come together, we must fight for those we ask to fight for us. We must stand up for our federal workers. We must stand up for veterans. We must stand up for immigrants. We must stand up for our queer and transgender siblings.

And we must stand up for the arts and humanities. For who among us has not been inspired by the journeys of the crew of the Starship Enterprise or the impossible struggle of a rebel alliance against an evil empire, a long time ago, in a galaxy far, far away?

In the words of a great freedom fighter: “rebellions are built on hope.”

In each of you today, I see the light of hope. And together, we can topple an empire.

---

~ Dr. Kylie Ariel Bemis
