---
title: "Hands Off Boston: 'Once there was a dream'"
date: April 5, 2025
---

***

Hello, my friends. Hello, America.

Once upon a time, there was a dream. A dream rising from the land of my ancestors, from before this was America. A dream so sacred and so inevitable that even Spanish colonizers and British colonizers could not deny it. A dream that so inspired America’s founders, they forged a new nation dedicated to its purpose.

Once, there was a dream consecrated in blood on the battlefield at Gettysburg and on Edmund Pettus Bridge in Selma. Once, a dream rang out from the steps of the Lincoln Memorial, and still it echoes today.

Now we are a nation trapped in a long nightmare. A tyrant lives in the White House. He sends swarms of officers to steal our neighbors off our streets. He imprisons us across seas for pretend offenses. He denies us our birthrights, our genders, and our bodily autonomies. He destroys our lives and our livelihoods with policies to harass us and eat out the substance of our communities.

This nightmare is not new to us. It is the soul of our nation. It has haunted us since colonization. It has haunted us since we first enslaved one another. It must haunt us lest we forget and grow lazy in our long march toward liberty.

But the dream of America is that America is ours to shape — ours to emancipate. And the truth of the matter is that we cannot be here to tell the agents of tyranny to take their hands off America; we must be here to rise, to reach out, and to put our own hands on our own country.

We must dedicate ourselves to each other, even as they try to divide us. We must dedicate ourselves to peace, even as they prepare to make war on us. We must dedicate ourselves to our dream of America, even as they label us radicals and rebels. We must find the bravery to say once again: “Give me liberty or give me death!”

Because we know our dream will rise. We here today must resolve — whether it takes a month, or a year, or one hundred years, for the sake of all the children born in America today and tomorrow and every day after — we will keep the dream alive. America will be free for all of us, or America will be free for none of us.

And America must be free.

Let that dream rise from the revolutionary roads of Boston to the majestic mountains and valleys of Los Angeles and every city and town in between, from the sacred land of my ancestors, from sea to shining sea, from our voices rising together today. Let us sing forever and always that America must be free! America must be free! America must be free!

---

~ Dr. Kylie Ariel Bemis
