---
title: "Good Trouble Lives On: 'Complete the revolution'"
date: July 17, 2025
---

***

We march today to make good trouble, but the true trouble is in the soul of this nation. The White House wants America to become the land of White Supremacy. Of robber barons and secret police forces. A child of immigrants in Milford can’t go to school without fearing arrest. A mother in Worcester is stolen off the street in front of her daughters. Our president has already incited a lynch mob to storm our Capitol and overturn the results of a free and fair election once before.

We face tyranny that may feel unprecedented. The American dream may feel like a distant fairy tale. But that has always been the reality for far too many of us, and we are here today to remind ourselves that freedom and equality have always been won through struggle. Good trouble has taken many forms in this land since before America was called America.

When my Pueblo ancestors sent runners from village to village carrying knotted ropes, undoing one knot each day, and on the undoing of the last knot, they rose up against their Spanish oppressors, that was good trouble.

When my two-spirit ancestor We’wha a łamana from the badger clan, traveled from Zuni to Washington, D.C., to meet with President Grover Cleveland, to be an ambassador to America, to be studied by white society while she studied them back, to understand the colonizer way of thinking in order to help her people survive it, that was good trouble.

When American soldiers marched on Zuni from Fort Wingate to occupy the village, to arrest the bow priests, to take the children, and my two-spirit ancestor We’wha stood up against them and was arrested and imprisoned in Los Lunas for a month, that was good trouble.

When my father, a grandson of Polish and Swedish immigrants fell in love with my Zuni mother, and they chose to marry each other in a decade when interracial marriage was still a dangerous and radical idea in so many parts of America, that too was good trouble. Because only profound love can heal the hate dividing our nation. Only dangerous and radical love can redeem the soul of America.

When we find ourselves staring down the barrels of death’s rifles and say “You may shoot me, but it is only your own soul you will kill, for you can never kill the spirit of all those who yearn for freedom and liberty and justice for all,” that will be good trouble, necessary trouble, because that is the dangerous and radical love that will save the soul of this nation and complete the revolution of 1776.

We may be afraid, but have hope. Good trouble, necessary trouble, is in the bones and blood of this nation. Because the legacy of good trouble is not solely the legacy of any single man, but of Americans of all races and creeds coming together and collectively saying “This is not good enough. We can do better. We must do better. The story is not finished yet, because the dream has not been realized yet.”

That is why we are here. To make good trouble and complete the revolution we have been fighting not just since 1776, but since 1492. Until the dream is realized, we will keep fighting. We will speak up and speak out. We will keep rising up until America rises with us and we are all free. That is the dream. That is the light. That is what’s right. That is our right. This is our fight. And what happens when we fight? (We win.)

---

~ Dr. Kylie Ariel Bemis
