---
title: "Memorial Day Rally for a Dream: 'Who is a person?'"
date: May 26, 2025
---

***

We have come together here in Boston on Memorial Day to renew our memories. We are here to renew the American dream.

160 years ago, our nation was embroiled in a great civil war over the question of “Who is a person?” in America. Today, the conscience of America is again bitterly enjoined in a brutal battle over the question of personhood.

When that civil war was ended with a decisive victory for the side of Justice, our nation observed the first Memorial Day — then called Decoration Day — to honor the Union soldiers who died defending Liberty and the proposition that all people are created equal. One month later, our forebears adopted an historic amendment declaring that “All persons born or naturalized in the United States, and subject to the jurisdiction thereof, are citizens of the United States.” Moreover, the framers of that amendment declared that “No state shall… deprive any person of life, liberty, or property, without due process of the law.”

Since then, we have waved goodbye to many more friends and relatives as they departed to fight for democracy and freedom on foreign shores, and we have wept and mourned them when they are returned to us, having fallen while defending the American dream of equality and Justice for all.

Today, we remember them.

Today, we remember brave Americans, like my mother’s uncle, Luther Ghahate, who was shot and killed in action while hanging from the skids of a helicopter hovering over Vietnam, who now rests with other warriors in Zuni Cemetery. We remember those who gave up their lives for freedom.

But we also remember those whose lives were taken in other ways. Yesterday marks the fifth anniversary of the cruel and racist murder of George Floyd at the hands of Minneapolis police officer Derek Chauvin. We remember that America rose up in righteous response to that brutal injustice, in the greatest wave of protests since the Civil Rights era.

Yet today, we are still a nation gripped by hate. We are still a nation with a guilty conscience troubled over the question of “Who is a person?” in America. We are once again embroiled in a great political war that will challenge the question of whether a nation like ours can long endure in this world.

Today, the President of the United States wages a merciless war against the immigrants of America. He sends swarms of officers into our state to terrorize our communities in Boston, Worcester, Framingham, Falmouth, New Bedford, and so many other cities across the Commonwealth.

Today, immigrants in America now live in constant fear of being ripped from their families and sent across seas to be imprisoned in foreign jails for imagined crimes. Americans are asked to watch as our friends and our neighbors are kidnapped off the street by agents of ICE. We are told that our local governments and our local police are powerless to stop this injustice. Our community members and even our elected officials are arrested for trying to stop it.

We are here on Memorial Day not only to remember our fallen American soldiers, but to honor their sacrifice by protecting the rights, liberties, and the American dream they died defending.

We are here to declare that “All persons” means “All persons.” Whether you’re Indigenous and your ancestors have always been here, or your ancestors were enslaved and brought here against their will, or your ancestors came here as immigrants, or you came here as an immigrant yourself, your right to life, liberty, and due process in America must not be infringed.

That is why we are here.

We are here on Beacon Hill to put the question to our governor and to our police departments and to all of our elected officials across the Commonwealth: what will you do to protect us and our communities from the terrorism of ICE?

Because we are here to boldly swear to each other that we will not be quiet. We the People will not allow a president who considers himself a king to terrorize our neighborhoods with a secret police force that acts outside the law and brutalizes our neighborhoods. We will not allow peace if there is no justice.

Because now is the time. Now is our time to stand up for the democracy and Liberty and the American dream our fallen heroes died defending. Now is our time to answer the profound hate dividing our nation with profound love for our neighbors. Now is the time to raise our voices and open our hearts. Now is our time to decide whether we have the courage of the American patriots who died for our freedom before us, or if we will let our democracy die in darkness.

For no person shall be President who, having previously taken an oath to support the Constitution of the United States, shall have engaged in insurrection or rebellion against it.

If we take up this struggle, we must recognize that the struggle for democracy is also a long struggle against hate, for none of us are free until all of us are free. Our collective humanity is intertwined with all of us whose personhood can be questioned. Either we are all persons, or none of us are.

When we go back home to our communities and neighborhoods, we must remember that we are not free until our immigrant neighbors are free, and our transgender neighbors are free, and our Black, Brown, and Indigenous neighbors are free, and our disabled neighbors are free.

That is the American dream for which we fight.

Because when we banish hatred from our hearts, and when we come together with our hearts and minds open to each other, and when we are accepting and full of profound love for all persons in America and around the world, and when we keep the courage to fight for Liberty and Justice for all, and when freedom rings from every corner of the Commonwealth and all across America, and the American dream is realized from sea to shining sea, and tyranny has no home here, then we will be free.

And that day will come. Because we believe it. Because we dream it. Because we will fight for it. Because America must be free.

America must be free.

---

~ Dr. Kylie Ariel Bemis
