---
title: "Saving Our Union: 'We the People'"
date: March 4, 2025
---

***

My fellow Americans and our welcome allies who have found a home on American soil: we are gathered here today on the land of the Wampanoag and Massachusetts Peoples, in one of the great cities where America was born nearly 250 years ago.

We are gathered here in Boston, because America is a nation in crisis. On this evening, in Washington, D.C., the president will address a joint session of Congress. But that address will not address this crisis — a crisis that threatens the very heart of America. That is why we are gathered here today: it has fallen to us, the American People, and our allies in democracy, to rise up and meet this crisis. We are here, because America is a free nation, because America is a democracy, and because we free Americans will not let our democracy die in darkness. We are here, because America has no kings.

And yet we find ourselves with a tyrant in the White House who fancies himself a king. We find ourselves with a president who has chosen not to faithfully execute the laws of our country, but has instead chosen to violate our Constitution again and again with his every executive action. We find ourselves with a president who has turned his back on our closest allies, and instead has aligned himself with the dictators of the world. We find ourselves with a president who has chosen not to keep the promises of America, but instead to sell America to the highest bidders. And even now, one of those billionaire bidders has embedded himself and his cronies in every agency of our federal government like a computer virus, poised to delete our civil services and dismantle our most vital institutions of health, science, and public safety.

But while what is happening in the White House is the most treasonous betrayal, there are men and women in our Courts and our Congress who have failed the American People as well. By enabling the tyrant in the White House and giving him license to believe he is above the law and, therefore, to crown himself king. By failing this test of leadership and failing to hold him accountable to Congress. By ignoring the Will of the People when we have raised our voices in town halls and state capitals across the country again and again to express in no uncertain terms, louder and louder, until it resounds in a single, unwavering voice: America has no kings.

It is no mistake that we are gathered here in Boston, in one of the places where the promissory note that became the American dream was first imagined, and where 251 years ago, the Sons of Liberty dressed as Mohawks, boarded ships, and threw crates of British tea into Boston Harbor. These brave revolutionaries dressed in redface not only to disguise their identities, but also to show that they were not British but Americans, and to symbolically sever their bonds as subjects to a tyrant king. And while our Constitution drew inspiration from the democracy of the Iroquois Confederacy, I also remember that within walking distance from here, the Old North Church stood not only as a beacon for freedom, but also as an institution of segregation where enslaved Black and Indigenous People worshipped separately from their masters.

And yet, as an Indigenous American, I have never felt more Hope than I do now.

Because I have my ancestors’ memory of America and the many Americas that came before now, stretching back before America was born, before America was a dream, and I know this land is Native land, and Native land is for the People. Because I know that 2,500 miles away from here in what is now New Mexico, my Pueblo ancestors rebelled and cast out our Spanish rulers rather than suffer their oppression. Because even though the threat to our American democracy is dire and profound, I believe in my blood that We the People can come together with a profound unity the likes of which has never before been seen in our country’s history.

Because America is not only a dream but a promise. Because all of our American sisters and brothers and siblings now know what Black and Indigenous Americans have always known: that it is up to us to hold America to its promise; that the dream flickers and dies when we grow too complacent in our sacred duty of keeping all of the lanterns of Liberty lit; that it is up to us to Save our Union when it is in dire distress.

Because four score and seven years after our founders brought forth, on this continent, a nation, conceived in Liberty, and dedicated to the proposition that all men are created equal, some brave Americans fought a war over that promise, and a great American signed a momentous decree called the Emancipation Proclamation.

Because the last time Americans united to stand against the forces of fascism, the brave Black and Indigenous Americans who went to war for America in Europe and the Pacific came home and found they still could not fairly cast their vote in a ballot box, but today we freely elect Black and Indigenous Americans to our public offices.

Because I grew up never knowing I had any choice but to be a boy, but I speak to you today not only as an Indigenous American but as a queer and transgender woman.

My fellow transgender Americans know all too well that the threat we face is an existential one. My fellow Indigenous Americans know all too well the signs of genocide. We know all too well that killing the transgender child to save the cisgender sensibility is no different than killing the Indian to save the man. We know the threat we face.

Because for 249 years, We the People have labored to bend the arc of the American dream toward justice and Liberty for all, but our White House is now occupied by liars, tyrants, and a would-be king who all wish to undo our centuries of progress, dismantle our civil rights, destroy the lives and Liberty of the People, and replace our democracy with a billionaires’ oligarchy.

And so I am here today to ask my fellow Americans to raise their voices and stand together against the forces of fascism and autocracy before it is too late.

I believe We the People can come together to Save our Union. I believe We the People can raise our voices in unison and say we hold these truths to be self-evident: that all People are created equal; that our government is instituted by the People to secure the rights of the People to Life, Liberty, and the pursuit of Happiness; that government of the People, by the People, and for the People is the promise of America; that America has no kings.

I believe We the People can come together to Save our Union before it is too late.

I believe We the People can come together and forge new bonds of community and kinship more unbreakable than ever before in our nation’s history.

I believe We the People will turn to our immigrant neighbors and our Black and Brown  and Indigenous neighbors, and our disabled neighbors, and our queer and transgender neighbors and say with profound love and cosmic responsibility: you are safe with me, and I will fight for you.

This is my great Hope, and tonight, you become messengers of Hope. We must not only raise our voices to our elected officials in Washington and in our state capitals and in our city halls; we must also speak to our friends and our loved ones and our neighbors. When we go home, we must get on the phone and talk not only with our senators and our representatives but also with our aunts and uncles and parents and siblings and peers.

Because We the People must hold America to its promises.

We the People must ensure America honors its treaties.

We the People must bend the arc of the American dream once again toward justice.

We the People will make our voices heard, and we will say in unison: America has no kings; democracy can never die so long as We the People fight for it; and we will never stop fighting until the American dream is birthed into reality. We will make our voices heard in every village, every town, and every city of this country; from the rolling hills of Boston to the windswept mountains of Waitsfield to the howling highways of Los Angeles; from the towering cities of New York and Chicago, to the sun-baked soil of Zuni Pueblo. We will make ourselves heard.

Because America is a promise born of the People, by the People, and for the People, and we shall not let that promise be broken.

---

~ Prof. Kylie Ariel Bemis
