---
title: "Show Pride for Democracy: 'Your liberty is my liberty'"
date: March 15, 2025
---

***

My fellow Americans and allies of democracy, we are gathered here on Wampanoag and Massachusetts land on a somber day. Last night, democracy died in America. Last night, democracy died in the Senate. Today, I’m sorry to say we no longer live in a republic.

Last year, the Supreme Court and John Roberts handed the tyrant in the White House a mighty sword. Last night, the Senate voted 62-38 to place a crown upon the tyrant’s head. So today, we inherit a heavy legacy. The Courts will not come to save us. Congress will not come to save us. Today, We the People have inherited the monumental responsibility of preserving our republic. We have inherited the momentous duty of breathing new life into the 249-year-old dream of America. So today, we stand united to raise our voices to say to the tyrant: America has no kings. Tyrants are not welcome here.

But first we must learn from the lessons that brought us here. We have learned the hard way that we must be ever vigilant against the voices calling for moderation. We must be vigilant against the voices saying “aren’t you overreacting?” We must be vigilant against the voices saying “it’s not the right time” or “we can’t fight every battle.”

To which I say: why can’t 300 million Americans fight every battle?

Because we cannot compromise in a fight for our freedoms. We cannot compromise in the fight for American liberty. We cannot compromise the very soul of our democracy. And never will we bend to tyrants.

We can never compromise whose freedom of speech we defend, or we become Columbia University, where young people are taken from their homes and imprisoned more than a thousand miles away under the threat of deportation without ever being charged with a crime, and where students now live in a state of terror, and all remaining auspices of academic freedom are being surrendered as tribute to the whims of a would-be king.

We can never compromise when or where transgender people can be our true selves — whether in bathrooms or in schools or on the fields of sport — because tyrants who seek to control our bodies in any one place also seek to control all bodies in all places. Because tyrants who put chains on transgender womanhood do it because they seek to put chains on all womanhood.

We can never compromise that the children born on American soil are themselves American, and that the greatness of America is that it is willed into being from the collective dream of all of its citizens no matter where we are born. Because my mother’s Zuni ancestors always lived in what is now New Mexico since long before America was born, and my father’s Polish ancestors traveled across the Atlantic from East Germany to Milwaukee, Wisconsin more than a hundred years ago, and I am only here today in Boston because — by the providence of the American dream — they found each other.

We can never compromise that America is the dream of Indigenous people who have always been here, and it is the dream of immigrants who came here seeking freedom, and it is the dream of Black people whose enslaved ancestors had no choice in the matter.

We must never forget that we are all Americans in this together, and when tyrants come for any of us, they come for all of us, because all of our fates are interconnected. So we must always say to ourselves: “Your liberty is my liberty. Your freedom is my freedom. Your struggle is my struggle.”

Now some of you may remember that 60 years and 6 days ago today, a brave group of about 600 Black Americans set out from Selma, Alabama to the state capital of Montgomery to demand the right to vote, and on climbing the crest of Edmund Pettus Bridge, they were met with fearsome and bloody brutality from white segregationists, the likes of which may soon stain all of America once again if the tyrant in the White House has his way.

What some of you may not remember is that in the wake of what became known as Bloody Sunday, clergy and citizens from all across America journeyed to Selma to join a second march to Montgomery.

Among them, a white minister named James Reeb traveled from Boston, Massachusetts to join the march in Selma. James Reeb lived in Roxbury, because, in his words, “you cannot make a difference for African Americans while living comfortably in a white community.” That second march from Selma was again turned away at the crest of Edmund Pettus Bridge, but later that evening, white segregationists cracked James Reeb's skull open. James Reeb died 2 days later. James Reeb’s murder led to the court order that protected a third march of people of all races who finally made the 54-mile trek from Selma to Montgomery where Dr. Martin Luther King, Jr. delivered a speech to over 25,000 Americans on the steps of the state capital.

But just as Boston blood was spilled in Selma for the American dream, let us not also forget that precipitating that third march, there were protests in 80 cities all across America, just as today we are but one of many protests all across our 50 states.

And we must not forget that even though we are committed to the course of nonviolence, that does not mean we will not bleed. Even though we are committed to peace, that does not mean we will not need to put our bodies in harm’s way or even sacrifice our lives for the freedoms of our fellow Americans. James Reeb understood that.

Indeed, the regime in Washington, D.C. already has blood on its hands. Thousands will die for lack of food and medicine from USAID, and some have already lost their lives for lack of oxygen to breathe, and babies who could have been healthy are now born with HIV. 

But even before those preventable tragedies transpired, early on the 27th of January in Syracuse, New York, a transgender veteran named Elisa Rae Shupe, the first American to receive a federal nonbinary gender marker, wrote a final letter to the world before wrapping herself in a transgender pride flag and breathing her last breath. “Fuck you, America!” she wrote. “I don’t want your hatred.”

Elisa Rae Shupe was denied the American dream. She was denied life. She was denied liberty. She was denied the pursuit of happiness.

“But,” she also wrote, “my death is not a surrender.”

“You cannot erase nonbinary and transgender people because you give birth to more of us each day.”

We will never forget Elisa Rae Shupe.

We will fight for her. We will fight for each other. We will fight to save our republic, because no one else will save it for us.

We will fight to defend our democracy, because all people are born yearning to be free, and we are all each others’ siblings.

Because your liberty is my liberty.

Because your freedom is my freedom.

Because your struggle is my struggle.

Because America is not defined by the tyrant in the White House. 

Because America is the dream of the People.

Because no lie can live forever, and tyrants are not welcome here.

Because when we go home tonight, we will all dream of freedom and liberty for all and our hope will become an unstoppable force and our love for each other will be unfathomably deep and unbreakable.

Because no matter what the Courts say, and no matter what Congress says, and no matter what the White House says, We the People will rise together and join our voices to say what we know to be true:

America has no kings.

---

~ Dr. Kylie Ariel Bemis
