---
title: "Hands Off Worcester Mothers: 'Give us due process'"
date: May 11, 2025
---

***

On Mother’s Day, we are here to petition our government for redress of the most dire of grievances: the cruel and violent separation of a mother from her daughters.

Who tore Augusta Clara’s mother from her daughters? Who arrested her 16-year-old sister as their mother was being abducted?

We know the masked agents of ICE stole Augusta Clara’s mother from her daughters on Eureka Street. We know members of the Worcester police pushed a teenage girl to the pavement before arresting her, even as her mother was being driven away from her life and into the most inaccessible Orwellian nightmare of ICE detention. We know the police even arrested a Worcester School Committee candidate who was only trying to protect this family.

But the hands that conspired to create this terror belong to more powerful people than the cowardly agents of ICE. Those hands belong to “border czar” Tom Homan and secretary of homeland security Kristi Noem. Those hands belong to the Republicans in Congress who refuse to take responsibility for the terror they’ve helped to create. Those hands belong to any Democrats in Congress who still question whether it’s the “right time” — politically speaking — to oppose the president’s so-called immigration policy.

Those guilty hands also belong to every single American citizen who could speak up in protest without fear of deportation but instead choose to remain silent and complacent rather than join the movement to resist tyranny.

But the guiltiest hands belong to the President of the United States who is powerful enough to wage war on America’s most poor, marginalized, and vulnerable residents but who is also so powerless that he is unable to pick up a phone and facilitate the return of Kilmar Abrego Garcia and hundreds of other immigrants that his administration has unlawfully trafficked to a foreign concentration camp across the sea in El Salvador. And the guilty hands also belong to John Roberts and the other justices of his Court who gave the president a blank check of power in place of the Constitution of the United States.

So we are here to demand the Constitution. We are here to demand the due process of the law that is guaranteed to every person on American soil, citizen or non-citizen, as is our Constitutional right. We are here to firmly declare that no person or agency is above the law.

Give us due process, and we will be one step closer to reclaiming a democracy that has been captured by tyrants.

Give us due process, and we will no longer need to protest the kidnapping of our community members without warrant or reason, because the agents of ICE will be forced to present a warrant and reason for their actions.

Give us due process, and we will no longer need to protest the unjust detention of our community members in concentration camps across seas and state borders, because they will be given the legal opportunity to defend themselves and demonstrate that they are neither violent criminals nor gang members.

Give us due process, and our lawyers will no longer need to search the country to find where their clients have been trafficked, because the government will be forced to act in good faith and with respect for the dignity of the people in their custody.

Give us due process, and all people now living on American soil will once again be free from the terror of being taken from the streets of their communities without recourse or redress or justice.

We must call these incidents for what they are. These abductions are terrorism. ICE is a state-sponsored terrorist organization. What other purpose has been served here? If the people being taken are “the worst of the worst,” then where is the government’s evidence? Why does the government ignore court orders?

Because the purpose is to promote terror, and the purpose of that terror is to take from us the natural rights and civil liberties guaranteed to us by the Constitution — not just to American citizens, but to all people on American soil. Because the purpose of this administration is to consolidate power in the office of the president at the expense of our democracy. Because our president believes himself to be a king rather than a servant of the people.

Our president’s supporters talk about rule of law, but what they support is not the rule of law, but the rule of man. One man. A true rule of law means that no one is above the law. Not the police. Not ICE. Not the President of the United States of America.

Our president’s supporters call us a mob. But if there was any mob in Worcester that day, it was a mob of ICE agents and Worcester police. They are the ones who disturbed the peace. They are the ones who brought chaos to this city when members of the Worcester community came together to protect a family from being torn apart.

Now Worcester police must make the same decision that all local law enforcement must make: who do you serve and protect? Do you serve and protect the members of your own community? Or do you serve and protect the agents of ICE? Will you live up to the American ideal that all people are created equal, and America must provide equal protection under the law, and that equal protection must mean respecting the right to due process? Or will you help the agents of ICE in promoting the terror and tyranny of a would-be king?

Our demand is due process. Our demand is that our own cities and our state governments refuse to cooperate with a terrorist agency acting outside the rule of law. If you believe in America, if you believe in the rule of law, then it is your patriotic duty to refuse to cooperate with ICE. It is your patriotic duty to refuse to intervene when your fellow American citizens act to protect their own community if you will not protect it for them.

Because this terror must end.

Now I know that our blood runs hot with righteous rage because we are faced with the gravest of injustices, and justice must be done. But in our enthusiasm for justice, we must not allow ourselves to drink from the same kool-aid of retribution as the perpetrators of these crimes. We must not allow ourselves to be baited into violence by the lips of instigators or the poisonous provocation of this administration. We must remain committed to nonviolence, because we are the ones dedicated to the rule of law. Because our demand is due process of the law, and the end of tyranny in America.

We will protest, and we will resist, and we will not let there be peace without justice, but we must remain nonviolent along the way; because we will show the rest of America who the real criminals are. We will show America that the only mob rule is the rule of ICE. We will show America that the only violence being perpetrated is the violence of the war this administration is waging against its own people, against democracy, and against America itself.

And when America wakes up, this terror will end. When America wakes up, this tyranny will end. Because America is better than this. America must be better than this. Because millions of immigrants across history — including Augusta Clara’s mother — have fled tyranny in their homelands for the dream of freedom in America, and the people of America will not let that dream be extinguished by a man who would be king.

Because we stand on Nipmuc land, and as an Indigenous person, I declare that if there is any legitimacy in America, it is that America must be the land of the free and America must become once again a land that welcomes immigrants and all peoples, or America itself is illegal.

So America must be free. The people of America must be free. We will fight for due process. We will fight for the Constitution. We will fight for rule of law. We will fight to re-unite the families separated by tyranny.

And when we fight, we win. Because the people united will never be defeated.

---

~ Dr. Kylie Ariel Bemis
