---
title: "Stand Up for Science: 'I am become Death'"
date: March 7, 2026
---

***

“And now I am become Death, the Destroyer of Worlds.”

These are words from the Bhagavad Gita, a Hindu epic poem that describes the conversation between a Prince and a God on the eve of war. They are also the words recalled by a scientist faced with the profound responsibility of unleashing the strong nuclear force and changing the world forever with the fire of atomic fission.

Today, we come together on the land of the Wampanoag, Nipmuc, and Massachusett people — from whom our Commonwealth appropriated its name — to stand up for science on an occasion that feels far too similar. But where do we as scientists find our morality in an immoral world?

One hundred years ago, our deterministic understanding of physics gave way to the uncomfortable probabilities of quantum mechanics, planting the seeds that would one day bloom into mushroom clouds over Hiroshima and Nagasaki in the summer of 1945, killing a quarter million souls, for the futile hope that two final atrocities would be enough to end not just one war but all wars.

Yet once again, we are lost in a world of dangerous probabilities, searching for the safety of certainty. Our Princes of War speak to Machine-Gods for guidance, and through the man-made magic of artificial intelligence, those probabilities transform into an enumeration of suggested military targets and their precise coordinates.

Last week, one of those targets was Shajareh Tayyebeh girls’ school in the Iranian city of Minab, where a US-Israeli airstrike killed at least 170 elementary school girls and staff. Merely hours before the strike, the makers of that Machine-God — named Claude by its Anthropic creators — warned our military leaders that artificial intelligence was not yet ready for life-and-death decisions, not yet knowing their warnings came on the eve of war.

What can we do as mere scientists in the face of such reckless abuse? We all choose science for a reason. To be a scientist is to believe in something greater than ourselves. To be a scientist is to seek an understanding of something beyond what we understood yesterday or today. Call it truth. Call it the Creator. Call it the universe. We all have our “why.” It’s no accident that Dr. Oppenheimer found meaning and guidance in the wisdom of Sanskrit poetry written over two thousand years before he was born. A scientist by another name is a Natural Philosopher.

I experienced the news that America was again at war at a symposium of Indigenous scientists in Tucson, Arizona. On the afternoon of war, Dr. Robin Wall Kimmerer, author of “Braiding Sweetgrass,” spoke to us of the reciprocity of nature and what we ask of each other. She spoke to us of a dream of braiding Western science with Indigenous science. Left to its own devices, Western science overwhelms the world with technology beyond our conscience or control. From the resurrection of prehistoric predators to the unleashing of artificial intelligence, our science fiction is rife with warnings of our technological hubris.

In the Western world, we speak of rights. In the Indigenous world, we speak of responsibilities. I am tired of my peers ignoring our responsibilities as scientists. I am tired of being told that politics has no place in science when scientists have a responsibility to be political. To stand up for science is not enough if we as scientists fail to stand up for civil society.

It is no mistake that Jewish scientists fleeing Germany built a bomb for America so that the Nazis couldn’t build it first. Today, we face a different Holocaust.

Yet still I believe in America. Because all of you are here. Because we are here. Because we feel the profound weight of responsibility. Because we are scientists. Because we are patriots. Because we are human.

I arrived in Boston early this morning from New Mexico — my own ancestral home as a Zuni Indian and also the home of the first nuclear detonation. Inspired by the poetry of John Donne, Dr. Oppenheimer called the test site “Trinity.” Some scientists believed the bomb could destroy the world. The sand there is still glass today, forever reflecting the choices we made.

Once again, America is poised to destroy the world. But the new world that takes its place has yet to be decided. Boston is no stranger to dreaming a brave new world. We have always been a city of rebels. The America we dreamt is already breaking. What will we do?

To paraphrase Dr. Kimmerer: To love America is not enough. We must find ways to heal it.

---

~ Dr. Kylie Ariel Bemis
