---
title: "All Writing"
---

***

### Fiction

- "Dreamborn." *Maiden Mother Crone: Fantastical Trans Femmes* (2019)
- "The Sixth World." *Transcendent 4: The Year's Best Transgender Themed Speculative Fiction* (2019)
- "The Sixth World." *Nameless Woman: An Anthology of Fiction by Trans Women of Color* (2018)

***

### Speeches

- [March 7, 2026 (Stand Up for Science)](speech-march-7-2026.html)
- [December 16, 2025 (Boston ICE Tea Party)](speech-december-16-2025.html)
- [November 15, 2025 (Rally for Truth, Light, and Courage)](speech-november-15-2025.html)
- [July 17, 2025 (Good Trouble Lives On)](speech-july-17-2025.html)
- [May 26, 2025 (Memorial Day Rally for a Dream)](speech-may-26-2025.html)
- [May 11, 2025 (Hands Off Worcester Mothers)](speech-may-11-2025.html)
- [April 5, 2025 (Hands Off Boston)](speech-april-5-2025.html)
- [March 15, 2025 (Show Pride for Democracy)](speech-march-15-2025.html)
- [March 7, 2025 (Stand Up for Science)](speech-march-7-2025.html)
- [March 4, 2025 (Saving Our Union)](speech-march-4-2025.html)

***

### Letters

- [Open Letter to Northeastern](letter-to-northeastern.html)
- [Open Letter to Academia](letter-to-academia.html)
- [Open Letter on Public Data](letter-on-public-data.html)
